version: "3.9"  # optional since v1.27.0
networks:
  tgl:
    external: true

services:
  app:
    container_name: 'adonis-tgl-app'
    build:
      context: .
      dockerfile: Dockerfile
    command: node ace serve --watch
    image: adonis-tgl
    volumes:
      - .:/usr/app
      - /usr/app/node_modules # anonymous volume for node_modules only
    networks:
      - tgl
    ports:
      - '3333:3333'
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: tgl
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: mysqld --innodb_use_native_aio=0 --default-authentication-plugin=mysql_native_password
    networks:
       - tgl
    volumes:
       - /usr/db/var/lib/mysql
