version: "3"
services:
  db:
    image: mysql:latest
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: adonis-tgl
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3308:3306'
  app:
    build: .
    command: node ace serve --watch
    environment:
      CHOKIDAR_USEPOLLING: 1
      NODE_ENV: development
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app
    depends_on:
      - db




